services:
  ultraviolet:
    image: diffusehyperion/ultraviolet
    container_name: ultraviolet
    restart: unless-stopped
    ports:
      - "8080:8080"
    
networks:
  default:
    name: ultraviolet